[package]
name = "tokio-shared-state-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["net", "io-util", "io-std", "rt-multi-thread", "rt", "macros", "time", "sync"] }
rand = "0.9.0-beta.1"